# Generated by Django 2.0 on 2020-06-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(default='NULL', max_length=250)),
                ('query_field', models.CharField(default='NO FIELD', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('STATUS', models.CharField(default='NO QUERY', max_length=100)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_students.students')),
            ],
        ),
    ]
