# Generated by Django 2.0 on 2020-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_students', '0002_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='STATUS',
            field=models.CharField(default='NO QUERY', max_length=100),
        ),
    ]
