# Generated by Django 2.0 on 2020-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_students', '0003_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='NEW_VALUE',
            field=models.CharField(default='NO QUERY RAISED', max_length=200),
        ),
    ]
