# Generated by Django 2.0 on 2020-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='PASSWORD',
            field=models.CharField(default='KIET123', max_length=250),
        ),
    ]
