# Generated by Django 2.0 on 2020-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200525_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=250)),
                ('PASSWORD', models.CharField(default='KIET123', max_length=250)),
                ('USERTYPE', models.CharField(default='S', max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
