# Generated by Django 2.0 on 2020-05-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='USERTYPE',
        ),
    ]
