# Generated by Django 2.0 on 2020-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_students_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
