# Generated by Django 2.0 on 2020-05-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200526_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='USER_NAME',
            field=models.CharField(default='NULL', max_length=250),
        ),
    ]
